services:
  injection-manager:
    build:
      context: .
    container_name: injection-manager
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]
